name: Create and publish a Docker image

on:
  push:
    # branches: ['main']
    tags:
      - '*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: m-housh

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/amd64 -t ${{ env.IMAGE_NAME }}:amd64 -f docker/Dockerfile .
      - run: docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:latest --append ${{ env.IMAGE_NAME }}:amd64

  build-arm:
    runs-on: ubuntu-aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/arm64 -t ${{ env.IMAGE_NAME }}:arm64 -f docker/Dockerfile .
      - run: docker buildx imagetools create --tag ${{ env.IMAGE_NAME }}:latest --append ${{ env.IMAGE_NAME }}:arm64

  finalize:
    runs-on: ubuntu-latest
    needs: [build-x86, build-arm]
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.CONTAINER_TOKEN }}
      - name: Create and push mutli-arch image
        run: |
          docker buildx imagetools create --append \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:amd64 \
            ${{ env.IMAGE_NAME }}:arm64

